sudo: false # force container-based infrastructure
language: node_js
node_js:
  - "5.5"

install:
  - npm install -g elm@0.16.0
  - npm install
  - elm-package install --yes

before_script:
  - export PATH=$PWD/node_modules/.bin/:$PATH
  - elm reactor &
  - npm run build

script: npm run test
