sudo: false # force container-based infrastructure
language: node_js
node_js:
  - "5.5"

install:
  - npm install -g elm@0.16.0
  - npm install
  - elm-package install --yes

before_script:
  - export PATH=$PWD/node_modules/.bin/:$PATH
  - npm run build
  - http-server '.' &
  # Wait for compilation is done.
  - until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:8080/index.html); do echo "." && sleep 1; done

script: npm run test
